apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cfg8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-cfg8@sha256:7bfcd37be2e60a1daf9cfce067978ea7a6f7641d87e83040e95524a9215df52b
        name: my-nodejs
        resources: {}
status: {}
